-- V1 baseline: full order-service schema as the JPA entities define it.
-- Mirrors what ddl-auto=update had created (lengths/types must match for validate).
-- No status CHECK constraint on purpose: the old one rejected new enum values
-- after the enum grew (PENDING→…→PAYMENT_FAILED). Statuses are validated in Java.

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_date TIMESTAMP(6),
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(19, 2)
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price_at_purchase NUMERIC(19, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    discount_type VARCHAR(255) NOT NULL,
    value NUMERIC(19, 2) NOT NULL,
    min_order_amount NUMERIC(19, 2),
    expiry_date TIMESTAMP(6),
    usage_limit INTEGER,
    times_used INTEGER
);
