-- V1 baseline: full product-service schema as the JPA entities define it.
-- Mirrors what ddl-auto=update had created (lengths/types must match for validate).
-- Check constraints deliberately omitted (they caused stale-enum outages before);
-- enum values are enforced in Java, not the DB.

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price NUMERIC(19, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    category VARCHAR(255),
    image_url VARCHAR(2048),
    version BIGINT,
    created_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment VARCHAR(2000),
    created_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS feature_flags (
    key VARCHAR(255) PRIMARY KEY,
    enabled BOOLEAN NOT NULL,
    description VARCHAR(255)
);
